name: opencv_dart
description: "OpenCV4 bindings for Dart language and Flutter, using dart:ffi. The most complete OpenCV bindings for Dart!"
version: 2.1.0-dev.0
homepage: https://github.com/rainyl/opencv_dart

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  ffi: ^2.1.2
  path: ^1.9.0
  native_assets_cli: ^0.7.2
  logging: ^1.2.0

dev_dependencies:
  ffigen: ^13.0.0
  test: ^1.25.2

topics:
  - opencv
  - image
  - ffi
  - flutter
